name: Build and release
on:
  push:
    branches:
      - dev
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm i
    - name: Bootstrap lerna
      run: npx lerna bootstrap
    - name: Build
      if: ${{ github.ref == 'refs/heads/dev' || github.event_name == 'pull_request' }}
      run: export CONNECTION_TYPE="REMOTE" && export TERMINUSDB_SERVER="https://cloud-dev.dcm.ist/" && export REACT_APP_BASE_ROUTER="" && npx lerna run build
    - name: Build prod
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        CONNECTION_TYPE="REMOTE" \
        TERMINUSDB_SERVER="https://cloud.terminusdb.com/" \
        REACT_APP_BASE_ROUTER="" \
        AUTH0_CLIENT_ID="365PsB0AmUmB2odSFwezWkX31BZv6PoH" \
        AUTH0_DOMAIN="terminus-cloud.eu.auth0.com" \
        npx lerna run build
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true
    - name: Upload tdb-dashboard dev
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/dev' }}
      run: gsutil cp -r packages/tdb-dashboard/dist/* "gs://dashboard-dev.terminusdb.com/"
    - name: Upload tdb-dashboard prod
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      run: gsutil cp -r packages/tdb-dashboard/dist/* "gs://dashboard.terminusdb.com/"
